name: mvpose
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - setuptools=39.1.0
  - easydict=1.9
  - seaborn=0.9.0
  - opencv=4.0.0       # conda-forge
  - requests=2.21.0
  - pytorch=1.0.1      # pytorch channel
  - torchvision=0.2.2  # pytorch channel
  - prettytable=0.7.2
  - numpy=1.16.2
  - tqdm=4.29.1
  - coloredlogs=10.0   # conda-forge
  - scipy=1.2.1
  - setproctitle=1.1.10
  - tensorflow=1.9.0   # conda-forge
  - visdom=0.1.8.8      # conda-forge
  - cython=0.29.6
  - ipython=7.6.13